export const actionTypes = {
    REQUEST_ALL_TODOS: 'REQUEST_ALL_TODOS',
    RECEIVE_ALL_TODOS: 'RECEIVE_ALL_TODOS',
    ADD_TODO: 'ADD_TODO',
    RECEIVE_ADDED_TODO: 'RECEIVE_ADDED_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    RECEIVE_UPDATED_TODO: 'RECEIVE_UPDATED_TODO',
    DELETE_TODO: 'DELETE_TODO',
    RECEIVE_DELETED_TODO: 'RECEIVE_DELETED_TODO',
    SEARCH_TODO: 'SEARCH_TODO',
}